name: uwgda2025
channels:
  - conda-forge
dependencies:
  - bokeh
  - cartopy
  - contextily
  - dask
  - dask-labextension
  - datashader
  - descartes
  - distributed
  - fiona
  - folium
  - fsspec
  - gcsfs
  - gdal
  - geojson
  - geopandas
  - geoviews
  - h5py
  - holoviews
  - hvplot
  - intake
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyterhub-singleuser 
  - jupyter-server-proxy
  - jupyterlab
  - matplotlib-base
  - matplotlib-scalebar
  - nbgitpuller
  - numpy
  - odc-stac
  - pandas
  - panel
  - parallel
  - pillow
  - pip
  - planetary-computer
  - pyogrio
  - pyproj
  - pystac
  - python
  - rasterio
  - rasterstats>=0.17.1
  - rio-cogeo
  - rioxarray
  - requests
  - s3fs
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - shapely
  - xarray-spatial
  - zarr 
#  - pip:
#    - easysnowdata
#
